//$file${.::generated_files::qm_files::active_objects::blinky::blinky.h} vvvvv
//
// Model: VPU_V100_CPU1.qm
// File:  ${.::generated_files::qm_files::active_objects::blinky::blinky.h}
//
// This code has been generated by QM 6.2.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// Copyright (c) 2005 Quantum Leaps, LLC
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for licensees
// interested in retaining the proprietary status of the generated code.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::generated_files::qm_files::active_objects::blinky::blinky.h} ^^
#ifndef BLINKY_H_
#define BLINKY_H_

#include "main_qm.h"

// Orthogonal Components

// AO definition

//$declare${active_objects::blinky} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${active_objects::blinky::blinky_state} ....................................
typedef enum blinky_state {
    BLINKY_STATE_INITIALIZATION,
    BLINKY_STATE_PRE_KERNEL,
    BLINKY_STATE_POST_KERNEL,
    BLINKY_STATE_WAITING_IO_EXPANDER,
    BLINKY_STATE_OPERATIRATION,
    BLINKY_STATE_LED_OFF,
    BLINKY_STATE_LED_ON,
}blinky_state_t;

//${active_objects::blinky::Blinky} ..........................................
typedef struct {
// protected:
    QActive super;

// private:
    QTimeEvt time_evt_half_cycle;

// public:
    blinky_state_t state;
} Blinky;

// protected:
QState Blinky_initial(Blinky * const me, void const * const par);
QState Blinky_OPERATION(Blinky * const me, QEvt const * const e);
QState Blinky_LED_OFF(Blinky * const me, QEvt const * const e);
QState Blinky_LED_ON(Blinky * const me, QEvt const * const e);
QState Blinky_INITIALIZATION(Blinky * const me, QEvt const * const e);
QState Blinky_PRE_KERNEL(Blinky * const me, QEvt const * const e);
QState Blinky_POST_KERNEL(Blinky * const me, QEvt const * const e);

//${active_objects::blinky::inst_ao_blinky} ..................................
extern Blinky inst_ao_blinky;

//${active_objects::blinky::globals::pointer_ao_blinky} ......................
extern QActive * const pointer_ao_blinky;

//${active_objects::blinky::globals::ao_blinky_ctor} .........................
// ! @brief constructor of the active object
// !
// ! @param pAO: pointer to the instance of the active object to be constructed;
// !
// ! This function is in charge of:
// ! - Proper construction of the Active object state machine calling the
// !   QActive_ctor function;
// ! - Call the constructor of the  orthogonal compoenets owned by this AO;
// ! - Construction of the time events owned by this active object;
// ! - Setting the initial value of any variables that demands it;
void ao_blinky_ctor(const QActive  * const pAO);

//${active_objects::blinky::globals::AO_BLINKY_MINIMAL_STACK_SIZE} ...........
// ! @brief Stack Size to this Active Object
// !
// ! - This Value must be larger than configMINIMAL_STACK_SIZE to FreeRTOS
// !   Compatibility
// ! - This Value must be largen tan any Stack use for any State + Substate
// !   from this Active Object;
// ! - If its Active Object Use Any Orthogonal Component, this value must be
// !   larger than any stack use for AO_State+AO_Substate+OC_State+OC_Substate
#define AO_BLINKY_MINIMAL_STACK_SIZE 300
//$enddecl${active_objects::blinky} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif
