//$file${.::generated_files::qm_files::active_objects::blinky::blinky.c} vvvvv
//
// Model: VPU_V100_CPU1.qm
// File:  ${.::generated_files::qm_files::active_objects::blinky::blinky.c}
//
// This code has been generated by QM 6.2.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// Copyright (c) 2005 Quantum Leaps, LLC
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for licensees
// interested in retaining the proprietary status of the generated code.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::generated_files::qm_files::active_objects::blinky::blinky.c} ^^

#include "./blinky.h"

S_DEFINE_THIS_MODULE("Blinky_AO");

//$declare${active_objects::errors::blinky_errors} vvvvvvvvvvvvvvvvvvvvvvvvvvv

//${active_objects::errors::blinky_errors} ...................................
enum blinky_errors {
    GOTTA_CATCH_EM_ALL_1 = 1U,
    GOTTA_CATCH_EM_ALL_2 = 2U,
};
//$enddecl${active_objects::errors::blinky_errors} ^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${active_objects::blinky} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${active_objects::blinky::Blinky} ..........................................

//${active_objects::blinky::Blinky::SM} ......................................
QState Blinky_initial(Blinky * const me, void const * const par) {
    //${active_objects::blinky::Blinky::SM::initial}
    return Q_TRAN(&Blinky_PRE_KERNEL);
}

//${active_objects::blinky::Blinky::SM::OPERATION} ...........................
QState Blinky_OPERATION(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${active_objects::blinky::Blinky::SM::OPERATION}
        case Q_ENTRY_SIG: {
            me->state = BLINKY_STATE_OPERATIRATION;

            QTimeEvt_armX(
                &me->time_evt_half_cycle,
                (uint16_t) (500),
                (uint16_t) (500)
            );

            status_ = Q_HANDLED();
            break;
        }
        //${active_objects::blinky::Blinky::SM::OPERATION::initial}
        case Q_INIT_SIG: {
            status_ = Q_TRAN(&Blinky_LED_OFF);
            break;
        }
        default: {
            //${active_objects::blinky::Blinky::SM::OPERATION::CATCH_ALL}
            if (e->sig < Q_USER_SIG) {
                status_ = Q_SUPER(&QHsm_top);
            }
            else {
                bsp_complementary_assert_data[0] = e->sig;

                S_ASSERT( GOTTA_CATCH_EM_ALL_2, 0 );

                /*
                                   _,........_
                               _.-'    ___    `-._
                            ,-'      ,'   \       `.
                 _,...    ,'      ,-'     |  ,""":`._.
                /     `--+.   _,.'      _.',',|"|  ` \`
                \_         `"'     _,-"'  | / `-'   l L\
                  `"---.._      ,-"       | l       | | |
                      /   `.   |          ' `.     ,' ; |
                     j     |   |           `._`"""' ,'  |__
                     |      `--'____          `----'    .' `.
                     |    _,-"""    `-.                 |    \
                     l   /             `.               F     l
                      `./     __..._     `.           ,'      |
                        |  ,-"      `.    | ._     _.'        |
                        . j           \   j   /`"""      __   |          ,"`.
                         `|           | _,.__ |        ,'  `. |          |   |
                          `-._       /-'     `L       .     , '          |   |
                              F-...-'          `      |    , /           |   |
                              |            ,----.     `...' /            |   |
                              .--.        j      l        ,'             |   j
                             j    L       |      |'-...--<               .  /
                             `     |       . __,,_    ..  |               \/
                              `-..'.._  __,-'     \  |  |/`._           ,'`
                                  |   ""       .--`. `--,  ,-`..____..,'   |
                                   L          /     \ _.  |   | \  .-.\    j
                                  .'._        l     .\    `---' |  |  || ,'
                                   .  `..____,-.._.'  `._       |  `--;"I'
                                    `--"' `.            ,`-..._/__,.-1,'
                                            `-.__  __,.'     ,' ,' _-'
                                                 `'...___..`'--^--'mh
                */
                status_ = Q_HANDLED();
            }
            break;
        }
    }
    return status_;
}

//${active_objects::blinky::Blinky::SM::OPERATION::LED_OFF} ..................
QState Blinky_LED_OFF(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${active_objects::blinky::Blinky::SM::OPERATION::LED_OFF}
        case Q_ENTRY_SIG: {
            me->state = BLINKY_STATE_LED_OFF;

            bsp_turn_off_led_1();
            bsp_force_task_8();

            status_ = Q_HANDLED();
            break;
        }
        //${active_objects::blinky::Blinky::SM::OPERATION::LED_OFF::HALF_CYCLE}
        case HALF_CYCLE_SIG: {
            status_ = Q_TRAN(&Blinky_LED_ON);
            break;
        }
        default: {
            status_ = Q_SUPER(&Blinky_OPERATION);
            break;
        }
    }
    return status_;
}

//${active_objects::blinky::Blinky::SM::OPERATION::LED_ON} ...................
QState Blinky_LED_ON(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${active_objects::blinky::Blinky::SM::OPERATION::LED_ON}
        case Q_ENTRY_SIG: {
            me->state = BLINKY_STATE_LED_ON;

            bsp_turn_on_led_1();
            bsp_force_task_8();
            status_ = Q_HANDLED();
            break;
        }
        //${active_objects::blinky::Blinky::SM::OPERATION::LED_ON::HALF_CYCLE}
        case HALF_CYCLE_SIG: {
            status_ = Q_TRAN(&Blinky_LED_OFF);
            break;
        }
        default: {
            status_ = Q_SUPER(&Blinky_OPERATION);
            break;
        }
    }
    return status_;
}

//${active_objects::blinky::Blinky::SM::INITIALIZATION} ......................
QState Blinky_INITIALIZATION(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${active_objects::blinky::Blinky::SM::INITIALIZATION}
        case Q_ENTRY_SIG: {
            me->state = BLINKY_STATE_INITIALIZATION;
            status_ = Q_HANDLED();
            break;
        }
        default: {
            //${active_objects::blinky::Blinky::SM::INITIALIZATION::CATCH_ALL}
            if (e->sig < Q_USER_SIG) {
                status_ = Q_SUPER(&QHsm_top);
            }
            else {
                bsp_complementary_assert_data[0] = e->sig;

                S_ASSERT( GOTTA_CATCH_EM_ALL_1, 0 );

                /*
                                   _,........_
                               _.-'    ___    `-._
                            ,-'      ,'   \       `.
                 _,...    ,'      ,-'     |  ,""":`._.
                /     `--+.   _,.'      _.',',|"|  ` \`
                \_         `"'     _,-"'  | / `-'   l L\
                  `"---.._      ,-"       | l       | | |
                      /   `.   |          ' `.     ,' ; |
                     j     |   |           `._`"""' ,'  |__
                     |      `--'____          `----'    .' `.
                     |    _,-"""    `-.                 |    \
                     l   /             `.               F     l
                      `./     __..._     `.           ,'      |
                        |  ,-"      `.    | ._     _.'        |
                        . j           \   j   /`"""      __   |          ,"`.
                         `|           | _,.__ |        ,'  `. |          |   |
                          `-._       /-'     `L       .     , '          |   |
                              F-...-'          `      |    , /           |   |
                              |            ,----.     `...' /            |   |
                              .--.        j      l        ,'             |   j
                             j    L       |      |'-...--<               .  /
                             `     |       . __,,_    ..  |               \/
                              `-..'.._  __,-'     \  |  |/`._           ,'`
                                  |   ""       .--`. `--,  ,-`..____..,'   |
                                   L          /     \ _.  |   | \  .-.\    j
                                  .'._        l     .\    `---' |  |  || ,'
                                   .  `..____,-.._.'  `._       |  `--;"I'
                                    `--"' `.            ,`-..._/__,.-1,'
                                            `-.__  __,.'     ,' ,' _-'
                                                 `'...___..`'--^--'mh
                */
                status_ = Q_HANDLED();
            }
            break;
        }
    }
    return status_;
}

//${active_objects::blinky::Blinky::SM::INITIALIZATION::PRE_KERNEL} ..........
QState Blinky_PRE_KERNEL(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${active_objects::blinky::Blinky::SM::INITIALIZATION::PRE_KERNEL}
        case Q_ENTRY_SIG: {
            me->state = BLINKY_STATE_PRE_KERNEL;

            QACTIVE_POST(
                &me->super,
                &im_kernel_start,
                &me->super
            );

            status_ = Q_HANDLED();
            break;
        }
        //${active_objects::blinky::Blinky::SM::INITIALIZATION::PRE_KERNEL::KERNEL_START}
        case KERNEL_START_SIG: {
            status_ = Q_TRAN(&Blinky_OPERATION);
            break;
        }
        default: {
            status_ = Q_SUPER(&Blinky_INITIALIZATION);
            break;
        }
    }
    return status_;
}

//${active_objects::blinky::Blinky::SM::INITIALIZATION::POST_KERNEL} .........
QState Blinky_POST_KERNEL(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${active_objects::blinky::Blinky::SM::INITIALIZATION::POST_KERNEL}
        case Q_ENTRY_SIG: {
            me->state = BLINKY_STATE_POST_KERNEL;
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&Blinky_INITIALIZATION);
            break;
        }
    }
    return status_;
}

//${active_objects::blinky::inst_ao_blinky} ..................................
Blinky inst_ao_blinky;

//${active_objects::blinky::globals::pointer_ao_blinky} ......................
QActive * const pointer_ao_blinky = &inst_ao_blinky.super;

//${active_objects::blinky::globals::ao_blinky_ctor} .........................
void ao_blinky_ctor(const QActive  * const pAO) {
    //=======================================//
    //=============Active-Object=============//
    //=======================================//

    // Casting the proper class of this AO
    Blinky * const me = (Blinky *) pAO;

    // Constructing the active object
    QActive_ctor(&me->super, Q_STATE_CAST(&Blinky_initial));

    //=======================================//
    //=========Orthogonal-Components=========//
    //=======================================//

    // in this example there isn't any orthogonal components

    // example
    // oc_test_ctor( me->oc_inst, &me->super , id);

    //=======================================//
    //==============Time-Events==============//
    //=======================================//

    QTimeEvt_ctorX( &( me->time_evt_half_cycle ) , &( me->super ) , HALF_CYCLE_SIG , 0U );

}
//$enddef${active_objects::blinky} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
