//$file${.::generated_files::qm_files::main_qm.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: VPU_V100_CPU1.qm
// File:  ${.::generated_files::qm_files::main_qm.h}
//
// This code has been generated by QM 6.2.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// Copyright (c) 2005 Quantum Leaps, LLC
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for licensees
// interested in retaining the proprietary status of the generated code.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::generated_files::qm_files::main_qm.h} ^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef MAIN_QM_H_
#define MAIN_QM_H_

#include "qpc.h"
#include "bsp_f28379d_xl_launchpad_cpu1.h"

#ifdef Q_SPY

#include "qs_config.h"

#endif

//================================================
//================Project-config==================
//================================================


//$declare${project_config} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${project_config::active_objects_priorities_enum} ..........................
enum active_objects_priorities_enum {
    // Priority in ascendance order
    IDLE_TASK=0U,
    AO_BLINKY_PRIO,
    AO_MAX_PRIORITY_PLUS_ONE
};

//${project_config::signals::publish_subcriber_signals_enum} .................
enum publish_subcriber_signals_enum {
    FIRST_PUBLISH_SIG = Q_USER_SIG,

    // Dont put any signal bellow this
    MAX_PUB_SIG,
};

//${project_config::signals::signals_enum} ...................................
enum signals_enum {
    // Common Signals
    KERNEL_START_SIG = MAX_PUB_SIG+1,

    // Blinky
    HALF_CYCLE_SIG,

};

//${project_config::QS::orthogonal_components_qs_id_enum} ....................
enum orthogonal_components_qs_id_enum {
    AO_NAME_OC_NAME_QS_ID = AO_MAX_PRIORITY_PLUS_ONE,
};

//${project_config::macros::time::RTOS_TICK_FREQUENCY_HZ} ....................
#define RTOS_TICK_FREQUENCY_HZ configTICK_RATE_HZ

//${project_config::macros::time::RTOS_TICK_PERIOD_MS} .......................
#define RTOS_TICK_PERIOD_MS (1000.f/RTOS_TICK_FREQUENCY_HZ)

//${project_config::event_types::orthogonal_compo~::OC_Evt} ..................
typedef struct {
// protected:
    QEvt super;

// public:
    uint16_t id;
} OC_Evt;

//${project_config::event_types::orthogonal_compo~::OC_TimeEvt} ..............
typedef struct {
// protected:
    QTimeEvt super;

// public:
    uint16_t id;
} OC_TimeEvt;

//${project_config::event_pools::EVT_POOL_1_SIZE} ............................
#define EVT_POOL_1_SIZE 32

//${project_config::event_pools::EVT_POOL_2_SIZE} ............................
#define EVT_POOL_2_SIZE 32

//${project_config::event_pools::EVT_POOL_3_SIZE} ............................
#define EVT_POOL_3_SIZE 32

//${project_config::event_pools::EVT_POOL_4_SIZE} ............................
#define EVT_POOL_4_SIZE 32


//${project_config::event_pools::evt_pool_payload_1_t} .......................
typedef struct {
// public:
    uint16_t data[1];
} evt_pool_payload_1_t;

//${project_config::event_pools::evt_pool_payload_2_t} .......................
typedef struct {
// public:
    uint16_t data[4];
} evt_pool_payload_2_t;

//${project_config::event_pools::evt_pool_payload_3_t} .......................
typedef struct {
// public:
    uint16_t data[8];
} evt_pool_payload_3_t;

//${project_config::event_pools::evt_pool_payload_4_t} .......................
typedef struct {
// public:
    uint16_t data[16];
} evt_pool_payload_4_t;

//${project_config::event_pools::EvtPool1_t} .................................
typedef struct {
// protected:
    QEvt super;

// private:
    evt_pool_payload_1_t payload;
} EvtPool1_t;

//${project_config::event_pools::EvtPool2_t} .................................
typedef struct {
// protected:
    QEvt super;

// private:
    evt_pool_payload_2_t payload;
} EvtPool2_t;

//${project_config::event_pools::EvtPool3_t} .................................
typedef struct {
// protected:
    QEvt super;

// private:
    evt_pool_payload_3_t payload;
} EvtPool3_t;

//${project_config::event_pools::EvtPool4_t} .................................
typedef struct {
// protected:
    QEvt super;

// private:
    evt_pool_payload_4_t payload;
} EvtPool4_t;

//${project_config::immutable_events::commum::im_kernel_start} ...............
extern QEvt const im_kernel_start;
//$enddecl${project_config} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


//================================================
//=================Active-Objects=================
//================================================

// Blinky

//$declare${active_objects::blinky::globals} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${active_objects::blinky::globals::pointer_ao_blinky} ......................
extern QActive * const pointer_ao_blinky;

//${active_objects::blinky::globals::ao_blinky_ctor} .........................
// ! @brief constructor of the active object
// !
// ! @param pAO: pointer to the instance of the active object to be constructed;
// !
// ! This function is in charge of:
// ! - Proper construction of the Active object state machine calling the
// !   QActive_ctor function;
// ! - Call the constructor of the  orthogonal compoenets owned by this AO;
// ! - Construction of the time events owned by this active object;
// ! - Setting the initial value of any variables that demands it;
void ao_blinky_ctor(const QActive  * const pAO);

//${active_objects::blinky::globals::AO_BLINKY_MINIMAL_STACK_SIZE} ...........
// ! @brief Stack Size to this Active Object
// !
// ! - This Value must be larger than configMINIMAL_STACK_SIZE to FreeRTOS
// !   Compatibility
// ! - This Value must be largen tan any Stack use for any State + Substate
// !   from this Active Object;
// ! - If its Active Object Use Any Orthogonal Component, this value must be
// !   larger than any stack use for AO_State+AO_Substate+OC_State+OC_Substate
#define AO_BLINKY_MINIMAL_STACK_SIZE 300
//$enddecl${active_objects::blinky::globals} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif
