//$file${.::generated_files::qm_files::qs_config.h} vvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: VPU_V100_CPU1.qm
// File:  ${.::generated_files::qm_files::qs_config.h}
//
// This code has been generated by QM 6.2.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// Copyright (c) 2005 Quantum Leaps, LLC
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for licensees
// interested in retaining the proprietary status of the generated code.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::generated_files::qm_files::qs_config.h} ^^^^^^^^^^^^^^^^^^^^^^^
#ifndef QS_CONFIG_H_
#define QS_CONFIG_H_

#ifdef Q_SPY

#include "main_qm.h"

//$declare${qs_config} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${qs_config::qs_filters_enum} ..............................................
//! @brief User Groups Enum.
enum qs_filters_enum {
    EXAMPLE_STATUS = QS_USER,
};

//${qs_config::application_qs_filter_config} .................................
//! @brief filter settings to trace.
//! just select whitch groups you would like to watch!!!
void application_qs_filter_config(void);

//${qs_config::application_dictionary_init} ..................................
//! @brief function to configure QS Dictionaries
//! This is a blocking function, please call it only from the initialization
void application_dictionary_init(void);
//$enddecl${qs_config} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif

#endif /* APPLICATION_INCLUDE_QS_CONFIG_H_ */

